### ISSUE TITLE
Формирование описания разработки

### ISSUE THREAD

**Issue by alehinsasha** [flex81/Final_HomeTask#2]
- [x] Коммиты с доступным описанием
- [x] Коммиты привязаны к issue

**Comment by flex81** [comment]
Как коммиты привязывать к issues? Ток к фичам в ST вроде можно?

**Comment by alehinsasha** [comment]
У коммита есть описание. Если в описании написать `#<номер issue>` то коммит привяжется к issue. Т.е. в SourceTree жмете кнопку "Закоммитить" автоматически переключаетесь на закладку "Состояние файлов" в поле где пишите описание комита (см. выше).

**Comment by flex81** [comment]
Ага, работает.
